# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoEuroTest' do
 
pod "SVProgressHUD"
pod "AFNetworking", '~> 3.0'
pod 'SDWebImage', '~>3.7'

end
